In [ ]:
lekcja 1

In [6]:
import pandas as pd
dane = {
    "nazwa": ["Laptop Dell", "Mysz Logitech", "Klawiatura Razer", "Monitor LG",
              "Słuchawki Sony", "Kubek termiczny", "Zeszyt A4", "Długopis Pilot",
              "Plecak miejski", "Powerbank Anker"],
    "cena": [3200.00, 89.99, 249.50, 899.00, 349.00, 45.00, 8.50, 4.20, 129.99, 99.90],
    "ilosc_na_stanie": [12, 45, 30, 15, 22, 60, 150, 200, 35, 40],
    "kategoria": ["Elektronika", "Elektronika", "Elektronika", "Elektronika",
                  "Elektronika", "Akcesoria", "Papiernicze", "Papiernicze",
                  "Akcesoria", "Elektronika"]
}
df = pd.DataFrame(dane)
df_first5 = df.head(5)
df['calkowita_wartosc'] = df['cena'] * df["ilosc_na_stanie"]
df

              nazwa     cena  ilosc_na_stanie    kategoria  calkowita_wartosc
0       Laptop Dell  3200.00               12  Elektronika           38400.00
1     Mysz Logitech    89.99               45  Elektronika            4049.55
2  Klawiatura Razer   249.50               30  Elektronika            7485.00
3        Monitor LG   899.00               15  Elektronika           13485.00
4    Słuchawki Sony   349.00               22  Elektronika            7678.00
5   Kubek termiczny    45.00               60    Akcesoria            2700.00
6         Zeszyt A4     8.50              150  Papiernicze            1275.00
7    Długopis Pilot     4.20              200  Papiernicze             840.00
8    Plecak miejski   129.99               35    Akcesoria            4549.65
9   Powerbank Anker    99.90               40  Elektronika            3996.00

In [7]:
lekcja 2

SyntaxError: invalid syntax (4079680775.py, line 1)

In [8]:
new_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
new_df.info()
new_df.describe()
sredni_wiek_pasazerow = new_df['Age'].mean()
print(f"Średni wiek pasażerów: {sredni_wiek_pasazerow}")

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB
Średni wiek pasażerów: 29.69911764705882

In [9]:
lekcja 3

SyntaxError: invalid syntax (2515027715.py, line 1)

In [ ]:
new_df_titanic = new_df[['Name', 'Age', 'Sex', 'Survived']]
new_df_titanic.head(10)
new_df_titanic.to_csv('pliczek.csv', index=False)

In [ ]:
lekcja 4

In [49]:
przezyl_ponizej_18 = new_df[(new_df['Age'] < 18) & (new_df['Survived'] == 1)]
liczba_osob_co_przezylo = len(przezyl_ponizej_18)
print(f"Liczba osób poniżej 18 lat, które przeżyły: {liczba_osob_co_przezylo}")
przezyl_ponizej_18[['Name', 'Age', 'Sex']].reset_index(drop=True)

Liczba osób poniżej 18 lat, które przeżyły: 61

                                        Name    Age     Sex
0        Nasser, Mrs. Nicholas (Adele Achem)  14.00  female
1            Sandstrom, Miss. Marguerite Rut   4.00  female
2                McGowan, Miss. Anna "Annie"  15.00  female
3                Nicola-Yarred, Miss. Jamila  14.00  female
4   Laroche, Miss. Simonne Marie Anne Andree   3.00  female
..                                       ...    ...     ...
56   Yasbeck, Mrs. Antoni (Selini Alexander)  15.00  female
57           Richards, Master. George Sibley   0.83    male
58                 Lines, Miss. Mary Conover  16.00  female
59           Johnson, Master. Harold Theodor   4.00    male
60          Najib, Miss. Adele Kiamie "Jane"  15.00  female

[61 rows x 3 columns]

In [ ]:
lekcja 5

In [64]:
new_df.isnull().sum() 
procent_brakow = (new_df.isnull().sum()  / len(new_df)) * 100
procent_brakow
kolumny_do_zachowania = procent_brakow[procent_brakow < 10].index
new_df = new_df[kolumny_do_zachowania]
new_df

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500,Q

In [ ]:
lekcja 6

In [76]:
srednia_wieku = new_df['Age'].mean()
new_df['Age'] = new_df['Age'].fillna(srednia_wieku)
new_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
lekcja 7

In [90]:
new_df2 = new_df.copy()
new_df2.sort_values(by='Age')
new_df2.dropna(inplace=True)
new_df2.sort_values(by='Age',inplace=True)
new_df_10_youngest = new_df2.head(10)
new_df_10_oldest = new_df2.tail(10)
new_df_10_oldest
new_df_10_youngest

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
305,306,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S
205,206,0,3,"Strom, Miss. Telma Matilda",female,2.00,0,1,347054,10.4625,G6,S
297,298,0,1,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.00,1,1,230080,26.0000,F2,S
193,194,1,2,"Navratil, Master. Michel M",male,3.00,1,1,230080,26.0000,F2,S
445,446,1,1,"Dodge, Master. Washington",male,4.00,0,2,33638,81.8583,A34,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
751,752,1,3,"Moor, Master. Meier",male,6.00,0,1,392096,12.4750,E121,S

In [ ]:
lekcja 8

In [117]:
new_df3 = new_df.copy()
new_df3 = new_df3.query("Fare > 50 and Pclass == 1").reset_index(drop=True)
liczba_pasazerow = new_df3.shape[0]
srednia_wartosc_biletow = new_df3['Fare'].mean()
liczba_pasazerow
print(f"Liczba pasażerów klasy 1, którzy zapłacili więcej niż 50: {liczba_pasazerow}")
print(f"Średnia wartość biletów dla tych pasażerów: {srednia_wartosc_biletow}")

Liczba pasażerów klasy 1, którzy zapłacili więcej niż 50: 139
Średnia wartość biletów dla tych pasażerów: 114.73878992805757

In [ ]:
zadanie 10

In [147]:
new_df4 = new_df.copy()
new_df5 = new_df.copy()
procent_missing = new_df4.isnull().sum() / new_df4.shape[0] * 100
zostaw_te_kolumny = procent_missing[procent_missing < 60].index
new_df4 = new_df4[zostaw_te_kolumny]
new_df4['Age'] = new_df4['Age'].fillna(new_df4['Age'].mean())
new_df4['Embarked'] = new_df4['Embarked'].fillna(new_df4['Embarked'].mode()[0])
new_df4 = new_df4.dropna()
new_df4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [ ]:
new_df5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [156]:
print('pierwszy dataframe')
print(new_df4['Age'].describe())
print('drugi dataframe')
print(new_df5['Age'].describe())

pierwszy dataframe
count    891.000000
mean      29.699118
std       13.002015
min        0.420000
25%       22.000000
50%       29.699118
75%       35.000000
max       80.000000
Name: Age, dtype: float64
drugi dataframe
count    714.000000
mean      29.699118
std       14.526497
min        0.420000
25%       20.125000
50%       28.000000
75%       38.000000
max       80.000000
Name: Age, dtype: float64

In [153]:
print(new_df4.shape)
print(new_df5.shape)

(891, 11)
(891, 12)

In [ ]:
zadanie 15

In [11]:
df10 = new_df.copy()
df10

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [17]:
onechunk = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv', chunksize=50)
pierwszy_chunk = next(onechunk)

In [29]:
total_passengers = 0
age_sum = 0
age_count = 0
survived_sum = 0

for chunk in pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv', chunksize=50):
    total_passengers += len(chunk) 
    age_sum += chunk['Age'].sum()
    age_count += chunk['Age'].notnull().sum()
    survived_sum += chunk['Survived'].sum()

avg_age = age_sum / age_count 
survival_rate = (survived_sum / total_passengers) * 100

In [32]:
full_df_total_passengers = len(df10)
avg_age_full_df = df10['Age'].mean()
survival_rate_full_df = (df10['Survived'].sum() / full_df_total_passengers) * 100

In [34]:
print(f"Średni wiek pasażerów (przetwarzanie w kawałkach): {avg_age}")
print(f"Średni wiek pasażerów (pełny DataFrame): {avg_age_full_df}")
print(f"calkowita liczba pasażerów (przetwarzanie w kawałkach): {total_passengers}")
print(f"calkowita liczba pasażerów (pełny DataFrame): {full_df_total_passengers}")
print(f"survival rate (przetwarzanie w kawałkach): {survival_rate}%")
print(f"survival rate (pełny DataFrame): {survival_rate_full_df}%")

Średni wiek pasażerów (przetwarzanie w kawałkach): 29.69911764705882
Średni wiek pasażerów (pełny DataFrame): 29.69911764705882
calkowita liczba pasażerów (przetwarzanie w kawałkach): 891
calkowita liczba pasażerów (pełny DataFrame): 891
survival rate (przetwarzanie w kawałkach): 38.38383838383838%
survival rate (pełny DataFrame): 38.38383838383838%